version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: plantrek-db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - plantrek-db-data:/var/lib/postgresql/data

  axonserver:
    image: axoniq/axonserver:latest
    container_name: axon-server
    environment:
      AXONIQ_AXONSERVER_STANDALONE: "true"
    ports:
      - "8024:8024" # HTTP port for Axon Server dashboard
      - "8124:8124" # gRPC port for Axon Server clients
    volumes:
      - axonserver-data:/axonserver/data
      - axonserver-events:/axonserver/events
      - axonserver-config:/axonserver/config

volumes:
  plantrek-db-data:
  axonserver-data:
  axonserver-events:
  axonserver-config:
