server:
  port: 0
  error:
    include-binding-errors: always
    include-message: always

spring:
  application:
    name: SearchService
  datasource:
    url: jdbc:postgresql://localhost:5432/search_db
    username: user
    password: super_user
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${instance-id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka